/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.MonHocController;
import controllers.MonHocSinhVienController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.MonHoc;

/**
 *
 * @author VanTuan
 */
public class DangKyHocPhanJPanel extends javax.swing.JPanel {

    ArrayList<MonHoc> ds = new ArrayList<>();
    String ma;
    public DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form DangKyHocPhanJPanel
     */
    public DangKyHocPhanJPanel(String ma) {
        initComponents();
        setSize(650,440);
        String[] columns= new String[]{"Tên môn", "Số tín chỉ", "Mã giáo viên"};
        model.setColumnIdentifiers(columns);
        jTableDanhSachMonHoc.setModel(model);
        jTableDanhSachMonHoc.setAutoCreateRowSorter(true);
        this.ma = ma;
        themData();
    }
    
    public void themData() {
        model.setRowCount(0);
        ds = MonHocController.getInstance().danhSachMH();
        for (MonHoc d : ds) {
            model.addRow(new String[] {
                d.getTenMonHoc(),
                d.getSoTinChi() + "",
                d.getMaGV()
            });
        }
        model.fireTableDataChanged();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDanhSachMonHoc = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableDanhSachMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDanhSachMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDanhSachMonHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDanhSachMonHoc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableDanhSachMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDanhSachMonHocMouseClicked
        int select = JOptionPane.showConfirmDialog(this,"Bạn có muốn đăng ký học phần này không?", "CONFIRM", JOptionPane.YES_NO_OPTION);
        if(select == JOptionPane.YES_OPTION){
            boolean kt = MonHocSinhVienController.getInstance().dangKyHocPhan(ds.get(jTableDanhSachMonHoc.getSelectedRow()), ma);
            if(kt)
                JOptionPane.showMessageDialog(jScrollPane1, "Đăng ký thành công!");
            else
                JOptionPane.showMessageDialog(jScrollPane1, "Học phần đã được đăng ký trước đó!");
        }
    }//GEN-LAST:event_jTableDanhSachMonHocMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDanhSachMonHoc;
    // End of variables declaration//GEN-END:variables
}
