/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import controllers.AdminController;
import controllers.GiaoVienController;
import controllers.SinhVienController;
import java.awt.Dimension;
import java.awt.Toolkit;
import models.GiaoVien;
import models.SinhVien;
/**
 *
 * @author VanTuan
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        setResizable(false);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        this.setLocation((screenWidth - this.getSize().width)/2, (screenHeight - this.getSize().height)/2);
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("src//images//logo_haui.png").getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH));
        jLabel2.setIcon(imageIcon);
        text_err.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_DangNhap = new javax.swing.JButton();
        btn_DangNhapAdmin = new javax.swing.JButton();
        btn_DangNhapGV = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        text_err = new javax.swing.JLabel();
        edt_matKhau = new javax.swing.JPasswordField();
        edt_TenDangNhap = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_haui.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tên đăng nhập:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu:");

        btn_DangNhap.setText("Đăng nhập");
        btn_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhapActionPerformed(evt);
            }
        });

        btn_DangNhapAdmin.setText("Admin");
        btn_DangNhapAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhapAdminActionPerformed(evt);
            }
        });

        btn_DangNhapGV.setText("Giáo viên");
        btn_DangNhapGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhapGVActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Hiện mật khẩu");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jButton4.setText("Quên mật khẩu");

        text_err.setBackground(new java.awt.Color(255, 255, 255));
        text_err.setForeground(new java.awt.Color(255, 51, 51));
        text_err.setText("  ");

        edt_matKhau.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(btn_DangNhap))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_DangNhapAdmin)
                                .addGap(32, 32, 32)
                                .addComponent(btn_DangNhapGV))
                            .addComponent(edt_matKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(edt_TenDangNhap)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(text_err, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(jButton4))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edt_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edt_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_err)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DangNhap)
                    .addComponent(btn_DangNhapAdmin)
                    .addComponent(btn_DangNhapGV))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhapActionPerformed
        if(edt_TenDangNhap.getText().trim() != "" && edt_matKhau.getPassword().length != 0) {
            text_err.setVisible(false);
            String tenDangNhap = edt_TenDangNhap.getText().trim();
            String matKhau = String.valueOf(edt_matKhau.getPassword()).trim();
            SinhVien sinhVien = SinhVienController.getInstance().sinhVienDangNhap(tenDangNhap, matKhau);
            if(sinhVien != null) {
                text_err.setVisible(false);
                TrangChuSinhVien trangChuSinhVien = new TrangChuSinhVien(sinhVien);
                trangChuSinhVien.setVisible(true);
                this.setVisible(false);
            }
            else {
                text_err.setVisible(true);
                text_err.setText("Tên đăng nhập hoặc mật khẩu không chính xác!");
            }
        }
        else {
            text_err.setVisible(true);
            text_err.setText("Chưa điền đầy đủ thông tin!");
        }
    }//GEN-LAST:event_btn_DangNhapActionPerformed

    private void btn_DangNhapAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhapAdminActionPerformed
        if(edt_TenDangNhap.getText().trim() != "" && edt_matKhau.getPassword().length != 0) {
            text_err.setVisible(false);
            String tenDangNhap = edt_TenDangNhap.getText().trim();
            String matKhau = String.valueOf(edt_matKhau.getPassword()).trim();
            int check = AdminController.getInstance().adminDangNhap(tenDangNhap, matKhau);
            if(check == 1) {
                TrangChuAdmin trangChuAdmin = new TrangChuAdmin(true);
                this.setVisible(false);
                trangChuAdmin.setVisible(true);
            }
            else {
                text_err.setVisible(true);
                text_err.setText("Tên đăng nhập hoặc mật khẩu không chính xác!");
            }
        }
        else {
            text_err.setVisible(true);
            text_err.setText("Chưa điền đầy đủ thông tin!");
        }
    }//GEN-LAST:event_btn_DangNhapAdminActionPerformed

    private void btn_DangNhapGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhapGVActionPerformed
        if(edt_TenDangNhap.getText().trim() != "" && edt_matKhau.getPassword().length != 0) {
            text_err.setVisible(false);
            String tenDangNhap = edt_TenDangNhap.getText().trim();
            String matKhau = String.valueOf(edt_matKhau.getPassword()).trim();
            GiaoVien giaoVien = GiaoVienController.getInstance().giaoVienDangNhap(tenDangNhap, matKhau);
            if(giaoVien != null) {
                TrangChuGiaoVien trangChuGiaoVien = new TrangChuGiaoVien(giaoVien);
                trangChuGiaoVien.setVisible(true);
                this.setVisible(false);
            }
            else {
                text_err.setVisible(true);
                text_err.setText("Tên đăng nhập hoặc mật khẩu không chính xác!");
            }
        }
        else {
            text_err.setVisible(true);
            text_err.setText("Chưa điền đầy đủ thông tin!");
        }
    }//GEN-LAST:event_btn_DangNhapGVActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()) 
            edt_matKhau.setEchoChar((char)0);
        else
            edt_matKhau.setEchoChar('*');
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangNhap;
    private javax.swing.JButton btn_DangNhapAdmin;
    private javax.swing.JButton btn_DangNhapGV;
    private javax.swing.JTextField edt_TenDangNhap;
    private javax.swing.JPasswordField edt_matKhau;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel text_err;
    // End of variables declaration//GEN-END:variables
}
