/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.MonHocController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import models.MonHoc;

/**
 *
 * @author YenLinh
 */
public class DanhSachMonHocJPanel extends javax.swing.JPanel {
    ArrayList<MonHoc> dsMH = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form DanhSachMonHocJPanel
     */
    public DanhSachMonHocJPanel() {
        initComponents();
        setSize(600,440);
        String[] columns= new String[]{"Mã môn học", "Tên môn học", "Số tín chỉ", "Mã giáo viên"};
        model.setColumnIdentifiers(columns);
        jTable1.setModel(model);
        jTable1.setEnabled(false);
        jTable1.setAutoCreateRowSorter(true);
        themDuLieu();
    }
    
    public void themDuLieu(){
        dsMH = MonHocController.getInstance().danhSachMH();
        model.setRowCount(0);
        for (MonHoc monHoc : dsMH) {
            model.addRow(new String[]{
                monHoc.getMaMon(),
                monHoc.getTenMonHoc(),
                monHoc.getSoTinChi() + "", 
                monHoc.getMaGV()
            });
        }
        model.fireTableDataChanged();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã môn học", "Tên môn học", "Số tín chỉ", "Mã giáo viên"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
