/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.CongNoController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import models.CongNo;

/**
 *
 * @author VanTuan
 */
public class DanhSachCongNoJPanel extends javax.swing.JPanel {
    ArrayList<CongNo> ds = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form DanhSachCongNoJPanel
     */
    public DanhSachCongNoJPanel() {
        initComponents();
        setSize(600, 440);
        String[] columns= new String[]{"Mã công nợ", "Số dư tài khoản", "Số tiền còn nợ", "Mã sinh viên"};
        model.setColumnIdentifiers(columns);
        jTableCongNo.setModel(model);
        jTableCongNo.setEnabled(false);
        jTableCongNo.setAutoCreateRowSorter(true);
        themData();
    }
    public void themData() {
        ds = CongNoController.getInstance().danhSachCongNo();
        model.setRowCount(0);
        for (CongNo d : ds) {
            model.addRow(new String[] {
                d.getMaCongNo(),
                d.getSoDuTaiKhoan() + "",
                d.getSoTienConNo() + "",
                d.getMaSV()
            });
        }
        model.fireTableDataChanged();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneCongNo = new javax.swing.JScrollPane();
        jTableCongNo = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableCongNo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã công nợ", "Số dư tài khoản", "Số tiền còn nợ", "Mã sinh viên"
            }
        ));
        jScrollPaneCongNo.setViewportView(jTableCongNo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneCongNo, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneCongNo, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneCongNo;
    private javax.swing.JTable jTableCongNo;
    // End of variables declaration//GEN-END:variables
}
