/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.GiaoVienController;
import controllers.LichThiController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import models.GiaoVien;

/**
 *
 * @author VanTuan
 */
public class DanhSachGiaoVienJPanel extends javax.swing.JPanel {
    ArrayList<GiaoVien> ds = new ArrayList<GiaoVien>();
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form DanhSachGiaoVien
     */
    public DanhSachGiaoVienJPanel() {
        initComponents();
        setSize(600, 440);
        String[] columns= new String[]{"Mã giáo viên", "Tên giáo viên", "Số điện thoại", "Bằng cấp", "Giới tính"};
        model.setColumnIdentifiers(columns);
        jTableGiaoVien.setModel(model);
        jTableGiaoVien.setEnabled(false);
        jTableGiaoVien.setAutoCreateRowSorter(true);
        ds = GiaoVienController.getInstance().danhSachGiaoVien();
        themData();
    }
    public void themData() {
        model.setRowCount(0);
        for (GiaoVien d : ds) {
            model.addRow(new String[] {
                d.getMaGV(),
                d.getTenGV(),
                d.getSDT(),
                d.getBangCap(),
                d.getGioiTinh()
            });
        }
        model.fireTableDataChanged();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGiaoVien = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableGiaoVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã giáo viên", "Tên giáo viên", "Số điện thoại", "Bằng cấp", "Giới tính"
            }
        ));
        jScrollPane2.setViewportView(jTableGiaoVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableGiaoVien;
    // End of variables declaration//GEN-END:variables
}
