/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.LichThiController;
import controllers.MonHocController;
import controllers.MonHocSinhVienController;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import models.DanhSachMonHoc;
import models.LichThi;
import models.MonHoc;
import models.SinhVien;

/**
 *
 * @author DELL
 */
public class LichThiJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LichThi
     */
    public ArrayList<LichThi> ds1 = new ArrayList<>();
    public DefaultTableModel model = new DefaultTableModel();
    public LichThiJPanel() {
        initComponents();
        setSize(600,440);
    }
    public LichThiJPanel(SinhVien sv){
        initComponents();
        setSize(600,440);
        String[] columns= new String[]{"Mã môn học","Tên môn học","Thời gian thi", "Ca thi", "Địa điểm thi"};
        model.setColumnIdentifiers(columns);
        jTable1.setModel(model);
        jTable1.setEnabled(false);
        ArrayList<DanhSachMonHoc> ds = new ArrayList<>();
        ds = MonHocSinhVienController.getInstance().getData(sv);
        LichThi lichThi = new LichThi();
        for(DanhSachMonHoc i: ds){
            lichThi = LichThiController.getInstance().getData(i.getMaLichThi());
            if(lichThi == null){
                continue;
            }
            ds1.add(lichThi);
        }
        themData();
    }
    public void themData() {
        model.setRowCount(0);
        for (LichThi lichThi : ds1) {
            MonHoc mh = MonHocController.getInstance().getData(lichThi.getMaMon());
            model.addRow(new String[] { lichThi.getMaMon(), mh.getTenMonHoc(), lichThi.getThoiGianThi(), lichThi.getCaThi(), lichThi.getDiaDiemThi()});
        }
        model.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MaMH", "Tên môn học", "Thời gian thi", "Ca thi", "Địa điểm thi"
            }
        ));
        jTable.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTable, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTable, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jTable;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
