/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import models.Diem;
import models.GiaoVien;

/**
 *
 * @author Administrator
 */
public class Quan_ly_thong_tin_giao_vien extends javax.swing.JPanel {

    /**
     * Creates new form Quan_ly_thong_tin_giao_vien
     */
    public Quan_ly_thong_tin_giao_vien(GiaoVien giaovien) {
        initComponents();
        setSize(544, 372);
        
        magv.setText(giaovien.getMaGV());
        tengv.setText(giaovien.getTenGV());
        bangcap.setText(giaovien.getBangCap());
        gioitinh.setText(giaovien.getGioiTinh());
        matkhau.setText(giaovien.getMatKhau());
        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        magv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tengv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bangcap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        gioitinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btncapnhat = new javax.swing.JButton();
        matkhau = new javax.swing.JPasswordField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Thông tin cá nhân");

        jLabel2.setText("Mã giáo viên");

        magv.setEnabled(false);

        jLabel3.setText("Tên giáo viên");

        tengv.setEnabled(false);
        tengv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tengvActionPerformed(evt);
            }
        });

        jLabel4.setText("Bằng cấp");

        bangcap.setEnabled(false);
        bangcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangcapActionPerformed(evt);
            }
        });

        jLabel5.setText("Giới tính");

        gioitinh.setEnabled(false);
        gioitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gioitinhActionPerformed(evt);
            }
        });

        jLabel6.setText("Mật khẩu");

        btncapnhat.setText("Cập nhật");
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(23, 23, 23)
                                .addComponent(magv, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(matkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                    .addComponent(bangcap)
                                    .addComponent(tengv)
                                    .addComponent(gioitinh)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(btncapnhat))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(magv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tengv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bangcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btncapnhat)
                .addGap(92, 92, 92))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tengvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tengvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tengvActionPerformed

    private void bangcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangcapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bangcapActionPerformed

    private void gioitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gioitinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gioitinhActionPerformed

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatActionPerformed
        if(matkhau.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống", "ERROT", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ArrayList<GiaoVien> dsgv=new ArrayList<>();
        FileInputStream fis=null;
        InputStreamReader reader=null;
        BufferedReader bufferedreader= null;
        try {
            fis=new FileInputStream("file//giaoVien.txt");
            reader=new InputStreamReader(fis, StandardCharsets.UTF_8);
            bufferedreader=new BufferedReader(reader);
            String line=null;
            while(null!=(line=bufferedreader.readLine())){
                if(line.isEmpty()){
                continue;
                
            }
                GiaoVien gv=new GiaoVien();
                gv.parse(line);
                dsgv.add(gv);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(quan_ly_lop_hoc_phan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(quan_ly_lop_hoc_phan.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            if(fis!=null){
                try {
                    fis.close();
                } catch (IOException ex) {
                    Logger.getLogger(quan_ly_lop_hoc_phan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(reader!=null){
                try {
                    reader.close();
                } catch (IOException ex) {
                    Logger.getLogger(quan_ly_lop_hoc_phan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(bufferedreader!=null){
                try {
                    bufferedreader.close();
                } catch (IOException ex) {
                    Logger.getLogger(quan_ly_lop_hoc_phan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        for (GiaoVien giaoVien : dsgv) {
            if(giaoVien.getMaGV().equals(magv.getText())){
                if(giaoVien.getMatKhau().equals(matkhau.getText())){
                    JOptionPane.showMessageDialog(this, "Mật khẩu mới phải khác mật khẩu cũ", "ERROT", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            int choice=JOptionPane.showConfirmDialog(this, "Xác nhận sửa thông tin", "Hỏi",JOptionPane.YES_NO_OPTION);
            if(choice==JOptionPane.NO_OPTION){
            return;
            }
                else{
                    giaoVien.setMatKhau(matkhau.getText());
                }
            }
        }
        try(PrintWriter pw =new PrintWriter(new File("file//giaoVien.txt"))) {
            int x=0;
            for (GiaoVien giaoVien : dsgv) {
                if(x==0){
                    pw.print(giaoVien.toString());
                    x=1;
                }else{
                    pw.print(giaoVien.toString2());
                }
            }

                
            
        } catch (Exception e) {
            System.out.println("Lỗi ghi file");
        }
    }//GEN-LAST:event_btncapnhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bangcap;
    private javax.swing.JButton btncapnhat;
    private javax.swing.JTextField gioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField magv;
    private javax.swing.JPasswordField matkhau;
    private javax.swing.JTextField tengv;
    // End of variables declaration//GEN-END:variables
}
