/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.LichThiController;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import models.LichThi;
import models.NewException;

/**
 *
 * @author VanTuan
 */
public class TaoLichThiJPanel extends javax.swing.JPanel {
    /**
     * Creates new form TaoLichThiJPanel
     */
    ArrayList<LichThi> dsLichThis = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    
    public TaoLichThiJPanel() {
        initComponents();
        setSize(600, 440);
        String[] columns= new String[]{"Mã lịch thi", "Thời gian thi", "Ca thi", "Địa điểm thi", "Mã môn học", "Số lượng thí sinh"};
        model.setColumnIdentifiers(columns);
        jTableLichThi.setModel(model);
    }
    
    public void themData() {
        model.setRowCount(0);
        for (LichThi lichThi : dsLichThis) {
            model.addRow(new String[] { lichThi.getMaLichThi(), lichThi.getThoiGianThi(), lichThi.getCaThi(), lichThi.getDiaDiemThi(), lichThi.getMaMon(), lichThi.getSoLuongThiSinh() + "" });
        }
        model.fireTableDataChanged();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_taoLichThi = new javax.swing.JButton();
        MaskFormatter f;
        try {
            f = new MaskFormatter("##/##/####");
            f.setPlaceholderCharacter('0');
            edt_ngayBD = new javax.swing.JFormattedTextField(f);
            edt_ngayBD.setColumns(12);
            edt_ngayKT = new javax.swing.JFormattedTextField(f);
            edt_ngayKT.setColumns(12);
            jScrollLichThi = new javax.swing.JScrollPane();
            jTableLichThi = new javax.swing.JTable();
            btn_luuLichThi = new javax.swing.JButton();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            edt_soSinhVien = new javax.swing.JTextField();

            setBackground(new java.awt.Color(255, 255, 255));

            jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel1.setText("Nhập khoảng thời gian có thể tạo lịch thi");

            jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel2.setText("Thời gian bắt đầu:");

            jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel3.setText("Thời gian kết thúc:");

            btn_taoLichThi.setText("Tạo lịch thi");
            btn_taoLichThi.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btn_taoLichThiActionPerformed(evt);
                }
            });

        } catch (ParseException ex) {
            Logger.getLogger(TaoLichThiJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        jScrollLichThi.setBackground(new java.awt.Color(255, 255, 255));
        jScrollLichThi.setBorder(null);

        jTableLichThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Mã lịch thi", "Thời gian thi", "Ca thi", "Địa điểm thi", "Mã môn học"
            }
        ));
        jScrollLichThi.setViewportView(jTableLichThi);

        btn_luuLichThi.setText("Lưu lịch thi");
        btn_luuLichThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuLichThiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số lượng sinh viên tối đa trong 1 phòng:");

        jLabel5.setText("*Ghi chú: - Ca1: Sáng");

        jLabel6.setText("- Ca2: Chiều");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollLichThi)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41)
                        .addComponent(edt_soSinhVien))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edt_ngayBD)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_taoLichThi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_luuLichThi))
                            .addComponent(edt_ngayKT, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edt_ngayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(edt_ngayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edt_soSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_taoLichThi)
                        .addComponent(btn_luuLichThi, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollLichThi, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_taoLichThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taoLichThiActionPerformed
        try {
            NewException.getInstance().checkTaoLichThi(edt_ngayBD.getText().trim(), edt_ngayKT.getText().trim(), edt_soSinhVien.getText().trim());
            dsLichThis = LichThiController.getInstance().taoLichThi(edt_ngayBD.getText(), edt_ngayKT.getText(), edt_soSinhVien.getText());
            if(dsLichThis != null) {
                if(dsLichThis.size() == 0)
                    JOptionPane.showMessageDialog(this, "Không có sinh viên nào đăng ký học!.", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
                themData();
            }
            else
                JOptionPane.showMessageDialog(this, "Không thể tạo lịch thi do không đủ thời gian.", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_taoLichThiActionPerformed

    private void btn_luuLichThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuLichThiActionPerformed
        if(dsLichThis.size() == 0)
            JOptionPane.showMessageDialog(this, "Chưa tạo lịch thi.", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        else {
            if(LichThiController.getInstance().luuLichThi(dsLichThis, edt_soSinhVien.getText()))
                JOptionPane.showMessageDialog(this, "Lưu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src//images//icon_complete.png"));
            else 
                JOptionPane.showMessageDialog(this, "Lưu không thành công.", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_luuLichThiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_luuLichThi;
    private javax.swing.JButton btn_taoLichThi;
    private javax.swing.JFormattedTextField edt_ngayBD;
    private javax.swing.JFormattedTextField edt_ngayKT;
    private javax.swing.JTextField edt_soSinhVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollLichThi;
    private javax.swing.JTable jTableLichThi;
    // End of variables declaration//GEN-END:variables
}
