/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.GiaoVienController;
import controllers.MonHocController;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import models.GiaoVien;
import models.MonHoc;
import models.NewException;

/**
 *
 * @author YenLinh
 */
public class ThemMonHocJPanel extends javax.swing.JPanel {
    ArrayList<GiaoVien> giaoViens;
    DefaultComboBoxModel model = new DefaultComboBoxModel();
    /**
     * Creates new form ThemMonHocJPanel
     */
    public ThemMonHocJPanel() {
        initComponents();
        setSize(622, 478);
        giaoViens = GiaoVienController.getInstance().danhSachGiaoVien();
        if(giaoViens == null)
            model.addElement("Không có giáo viên nào.");
        else {
            for (GiaoVien giaoVien : giaoViens) {
                model.addElement(giaoVien.getMaGV() + " - " + giaoVien.getTenGV());
            }
        }
        jComboBoxMaGiaoVien.setModel(model);
        jComboBoxMaGiaoVien.setSelectedIndex(0);
        jComboBoxMaGiaoVien.setMaximumRowCount(4);
    }

    public void clear() {
        edt_maMonHoc.setText("");
        edt_tenMonHoc.setText("");
        edt_soTinChi.setText("");
        jComboBoxMaGiaoVien.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_themMonHoc = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxMaGiaoVien = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        edt_maMonHoc = new javax.swing.JTextField();
        edt_tenMonHoc = new javax.swing.JTextField();
        edt_soTinChi = new javax.swing.JTextField();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã môn học:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên môn học:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Số tín chỉ:");

        btn_themMonHoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_themMonHoc.setText("Thêm môn học");
        btn_themMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themMonHocActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_MonHoc.png"))); // NOI18N

        jComboBoxMaGiaoVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mã giáo viên:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxMaGiaoVien, 0, 298, Short.MAX_VALUE)
                            .addComponent(btn_themMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edt_maMonHoc)
                            .addComponent(edt_tenMonHoc)
                            .addComponent(edt_soTinChi))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edt_maMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edt_tenMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edt_soTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMaGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(104, 104, 104)
                .addComponent(btn_themMonHoc)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themMonHocActionPerformed
        try {
            NewException.getInstance().checkThemMH(edt_maMonHoc.getText(), edt_tenMonHoc.getText(), edt_soTinChi.getText());
            if(jComboBoxMaGiaoVien.getItemAt(jComboBoxMaGiaoVien.getSelectedIndex()) == "Không có giáo viên nào.") {
                JOptionPane.showMessageDialog(this, "Chưa có giáo viên!", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            }
            else {
                MonHoc monHoc = new MonHoc(edt_maMonHoc.getText(), edt_tenMonHoc.getText(), Integer.parseInt(edt_soTinChi.getText()) , jComboBoxMaGiaoVien.getItemAt(jComboBoxMaGiaoVien.getSelectedIndex()).split("-")[0].trim());
                boolean check = MonHocController.getInstance().themMonHoc(monHoc);
                if(check) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công môn học!", "Thông báo", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src//images//icon_complete.png"));
                    clear();
                }
                else 
                    JOptionPane.showMessageDialog(this, "Mã môn học này đã tồn tại!", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_themMonHocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_themMonHoc;
    private javax.swing.JTextField edt_maMonHoc;
    private javax.swing.JTextField edt_soTinChi;
    private javax.swing.JTextField edt_tenMonHoc;
    private javax.swing.JComboBox<String> jComboBoxMaGiaoVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
