/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.SinhVienController;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import models.SinhVien;

/**
 *
 * @author DELL
 */
public class ThongTinCaNhanSVJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinCaNhanSVJPanel
     */
    SinhVien sv;
    public ThongTinCaNhanSVJPanel() {
        initComponents();
        setSize(600,440);
    }
    public ThongTinCaNhanSVJPanel(SinhVien sv) {
        initComponents();
        setSize(600,440);
        txtma.setText(sv.getMaSV());
        txtten.setText(sv.getTenSV());
        txtgioitinh.setText(sv.getGioiTinh());
        txtngaysinh.setText(sv.getNgaySinh());
        txtsdt.setText(sv.getSDT());
        txtsothich.setText(sv.getSoThich());
        txtma.setEnabled(false);
        txtten.setEnabled(false);
        txtngaysinh.setEnabled(false);
        txtgioitinh.setEnabled(false);
        this.sv = new SinhVien(txtsdt.getText(), txtsothich.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        txtma = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        txtgioitinh = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        txtsothich = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin cá nhân");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Mã sinh viên");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Tên sinh viên");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Ngày sinh");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Giới tính");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Số điện thoại");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Sở thích");

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Sửa thông tin cá nhân");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaThongTinCaNhan(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsothich, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel1))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtsothich, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_suaThongTinCaNhan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaThongTinCaNhan
        try{
            if(txtsdt.getText().length() == 0){
                throw new Exception("Số điện thoại không được để trống");
            } else {
                int select = JOptionPane.showConfirmDialog(this,"Bạn có muốn thay đổi thông tin không?", "CONFIRM", JOptionPane.YES_NO_OPTION);
                if(select == JOptionPane.YES_OPTION){
                    try {
                        File file = new File("file//sinhVien.txt");
                        File file1 = new File("file//sinhVienTG.txt");
                        FileReader fr = new FileReader(file);
                        FileWriter fw = new FileWriter(file1);
                        BufferedReader br = new BufferedReader(fr);
                        String line;
                        int dem = 0;
                        while((line = br.readLine()) != null) {
                            fw.write("\n" + line);
                            dem++;
                        }
                        br.close();
                        fw.close();
                        fr.close();
                        FileReader fr1 = new FileReader(file1);
                        FileWriter fw1 = new FileWriter(file);
                        BufferedReader br1 = new BufferedReader(fr1);
                        br1.readLine();
                        while((line = br1.readLine()) != null) {
                            dem--;
                            String arr[] = line.trim().split("-");
                            if(txtma.getText().compareTo(arr[0].trim())==0){
                                String sothich = "Chưa cập nhật";
                                if(txtsothich.getText().length() != 0){
                                    sothich = txtsothich.getText();
                                }
//                                line = line.split("-")[0].trim() + "-" + line.split("-")[1].trim() + "-" + line.split("-")[2].trim() + "-" + line.split("-")[3].trim()
//                                        + "-" +  line.split("-")[4].trim() + "-" + line.split("-")[5].trim() + "-" + txtsdt.getText() + "-" + sothich;
                                try{
                                    if(!SinhVienController.checkSDT(txtsdt.getText())){
                                        System.out.println("ABC");
                                        throw new Exception("Số điện thoại không hợp lệ");
                                    }
                                    line = line.split("-")[0].trim() + "-" + line.split("-")[1].trim() + "-" + line.split("-")[2].trim() + "-" + line.split("-")[3].trim()
                                       + "-" +  line.split("-")[4].trim() + "-" + line.split("-")[5].trim() + "-" + txtsdt.getText() + "-" + sothich;
                                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                                }catch(Exception e){
                                    JOptionPane.showMessageDialog(this, e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
}
                                
                            }
                            if(dem == 0)
                                fw1.write(line);
                            else
                                fw1.write(line + "\n");
                        }
                        br1.close();
                        fw1.close();
                        fr1.close();
                        file1.delete();
                        sv.setSDT(txtsdt.getText());
                        sv.setSoThich(txtsothich.getText());
                        
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(ThongTinCaNhanSVJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    } catch(IOException ex){
                        Logger.getLogger(ThongTinCaNhanSVJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else {
                    txtsdt.setText(sv.getSDT());
                    txtsothich.setText(sv.getSoThich());
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_suaThongTinCaNhan


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtgioitinh;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtsothich;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
}
