/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.SinhVien;

/**
 *
 * @author DELL
 */
public class TrangChuSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuSinhVien
     */
    SinhVien sv;
    TrangChuiJPanel trangChuiJPanel;
    DanhSachDiemSinhVienJPanel danhSachDiemSinhVienJPanel;
    LichThiJPanel lichThiJPanel;
    CongNoJPanel congNoJPanel;
    ThongTinCaNhanSVJPanel thongTinCaNhanSVJPanel;
    DangKyHocPhanJPanel dangKyHocPhanJPanel;
    public TrangChuSinhVien() {
        if(sv == null){
            DangNhap dangNhap = new DangNhap();
            dangNhap.setVisible(true);
            this.setVisible(false);
        }
    }
    public TrangChuSinhVien(SinhVien sv){
        this.sv = sv;
        initComponents();
        setResizable(false);
        setSize(910,600);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int screenHeight = screenSize.height;
        int screenWidth = screenSize.width;
        this.setLocation((screenWidth - this.getSize().width)/2, (screenHeight - this.getSize().height)/2);
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("src//images//logo_haui.png").getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH));
        logo.setIcon(imageIcon);
        tensinhvien.setText(sv.getTenSV());
        khoitao(sv);
    }
    private void khoitao(SinhVien sv){
        //chucnang
        trangChuiJPanel = new TrangChuiJPanel();
        jPanelMain.add(trangChuiJPanel);
        
        lichThiJPanel = new LichThiJPanel(sv);
        jPanelMain.add(lichThiJPanel);
        lichThiJPanel.setVisible(false);
        
        dangKyHocPhanJPanel = new DangKyHocPhanJPanel(sv.getMaSV());
        jPanelMain.add(dangKyHocPhanJPanel);
        dangKyHocPhanJPanel.setVisible(false);
    }
    public void hienThi(JPanel jPanel){
        trangChuiJPanel.setVisible(false);
        if(danhSachDiemSinhVienJPanel != null)
            danhSachDiemSinhVienJPanel.setVisible(false);
        lichThiJPanel.setVisible(false);
        if(congNoJPanel != null)
            congNoJPanel.setVisible(false);
        if(thongTinCaNhanSVJPanel != null)
            thongTinCaNhanSVJPanel.setVisible(false);
        dangKyHocPhanJPanel.setVisible(false);
        jPanel.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        tensinhvien = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        btn_DangKyHocPhan = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_subject.png"))); // NOI18N
        jButton1.setText("Kết quả học tập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hienThiKQHT(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Tài chính");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hienThiCongNo(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Lịch thi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hienThiLichThi(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Thông tin cá nhân");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showThongTinCaNhan(evt);
            }
        });

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cổng thông tin sinh viên");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/logo_haui.png"))); // NOI18N

        tensinhvien.setText("Your name");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tensinhvien)
                .addGap(70, 70, 70))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHeaderLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tensinhvien))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Đăng xuất");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logOutClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        btn_DangKyHocPhan.setBackground(new java.awt.Color(255, 255, 255));
        btn_DangKyHocPhan.setText("Đăng ký học phần");
        btn_DangKyHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangKyHocPhanbtn_showThongTinCaNhan(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_DangKyHocPhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_DangKyHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_showThongTinCaNhan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showThongTinCaNhan
        if(thongTinCaNhanSVJPanel != null)
            jPanelMain.remove(thongTinCaNhanSVJPanel);
        thongTinCaNhanSVJPanel = new ThongTinCaNhanSVJPanel(sv);
        jPanelMain.add(thongTinCaNhanSVJPanel);
        thongTinCaNhanSVJPanel.setVisible(false);
        hienThi(thongTinCaNhanSVJPanel);
    }//GEN-LAST:event_btn_showThongTinCaNhan

    private void btn_hienThiLichThi(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hienThiLichThi
        hienThi(lichThiJPanel);
    }//GEN-LAST:event_btn_hienThiLichThi

    private void btn_hienThiKQHT(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hienThiKQHT
        if(danhSachDiemSinhVienJPanel != null)
            jPanelMain.remove(danhSachDiemSinhVienJPanel);
        danhSachDiemSinhVienJPanel = new DanhSachDiemSinhVienJPanel(sv);
        jPanelMain.add(danhSachDiemSinhVienJPanel);
        danhSachDiemSinhVienJPanel.setVisible(false);
        hienThi(danhSachDiemSinhVienJPanel);
    }//GEN-LAST:event_btn_hienThiKQHT

    private void btn_logOutClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logOutClicked
        DangNhap dn = new DangNhap();
        this.setVisible(false);
        dn.setVisible(true);
    }//GEN-LAST:event_btn_logOutClicked

    private void btn_hienThiCongNo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hienThiCongNo
        if(congNoJPanel != null)
            jPanelMain.remove(congNoJPanel);
        congNoJPanel = new CongNoJPanel(sv);
        jPanelMain.add(congNoJPanel);
        congNoJPanel.setVisible(false);
        hienThi(congNoJPanel);
    }//GEN-LAST:event_btn_hienThiCongNo

    private void btn_DangKyHocPhanbtn_showThongTinCaNhan(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangKyHocPhanbtn_showThongTinCaNhan
        hienThi(dangKyHocPhanJPanel);
    }//GEN-LAST:event_btn_DangKyHocPhanbtn_showThongTinCaNhan

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangKyHocPhan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel tensinhvien;
    // End of variables declaration//GEN-END:variables

}
