/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.GiaoVienController;
import controllers.SinhVienController;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.GiaoVien;
import models.SinhVien;

/**
 *
 * @author VanTuan
 */
public class XoaTaiKhoanJPanel extends javax.swing.JPanel {

    ArrayList<SinhVien> dsSinhVien = new ArrayList<>();
    ArrayList<GiaoVien> dsGiaoVien = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * Creates new form XoaTaiKhoanJPanel
     */
    public XoaTaiKhoanJPanel() {
        initComponents();
        setSize(600, 440);
        jRadioGiaoVien.setSelected(true);
        String[] columns= new String[]{"Mã tài khoản", "Tên tài khoản"};
        model.setColumnIdentifiers(columns);
        jTableDanhSach.setModel(model);
        jTableDanhSach.setAutoCreateRowSorter(true);
        hienThiGV();
    }

    public void hienThiGV() {
        dsGiaoVien = GiaoVienController.getInstance().danhSachGiaoVien();
        model.setRowCount(0);
        for (GiaoVien giaoVien : dsGiaoVien) {
            model.addRow(new String[] {
                giaoVien.getMaGV(),
                giaoVien.getTenGV()
            });
        }
        model.fireTableDataChanged();
    }
    
    public void hienThiSV() {
        dsSinhVien = SinhVienController.getInstance().danhSachSinhVien();
        model.setRowCount(0);
        for (SinhVien sinhVien : dsSinhVien) {
            model.addRow(new String[] {
                sinhVien.getMaSV(),
                sinhVien.getTenSV()
            });
        }
        model.fireTableDataChanged();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btn_xoaTaiKhoan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioGiaoVien = new javax.swing.JRadioButton();
        jRadioSinhVien = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDanhSach = new javax.swing.JTable();
        edt_maSinhVien = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(622, 461));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mã tài khoản:");

        btn_xoaTaiKhoan.setText("Xóa");
        btn_xoaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaTaiKhoanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Loại tài khoản:");

        jRadioGiaoVien.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioGiaoVien);
        jRadioGiaoVien.setText("Giáo viên");
        jRadioGiaoVien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioGiaoVienItemStateChanged(evt);
            }
        });

        jRadioSinhVien.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioSinhVien);
        jRadioSinhVien.setText("Sinh viên");
        jRadioSinhVien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioSinhVienItemStateChanged(evt);
            }
        });

        jTableDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã sinh viên", "Tên sinh viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableDanhSach);
        if (jTableDanhSach.getColumnModel().getColumnCount() > 0) {
            jTableDanhSach.getColumnModel().getColumn(0).setResizable(false);
            jTableDanhSach.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableDanhSach.getColumnModel().getColumn(1).setResizable(false);
            jTableDanhSach.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioGiaoVien)
                                        .addGap(66, 66, 66)
                                        .addComponent(jRadioSinhVien))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(edt_maSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(btn_xoaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioSinhVien))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edt_maSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_xoaTaiKhoan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_xoaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaTaiKhoanActionPerformed
        String ma = edt_maSinhVien.getText().trim();
        if(jRadioGiaoVien.isSelected()) {
            if(GiaoVienController.getInstance().xoaGiaoVien(ma)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!","Thông báo", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src//images//icon_complete.png"));
            } else {
                JOptionPane.showMessageDialog(this, "Không tồn tại hoặc sai mã giáo viên!","Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            }
            hienThiGV();
        }
        else {
            if(SinhVienController.getInstance().xoaSinhVien(ma)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!","Thông báo", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src//images//icon_complete.png"));
            } else {
                JOptionPane.showMessageDialog(this, "Không tồn tại hoặc sai mã sinh viên!","Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            }
            hienThiSV();
        }
    }//GEN-LAST:event_btn_xoaTaiKhoanActionPerformed

    private void jRadioGiaoVienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioGiaoVienItemStateChanged
        hienThiGV();
    }//GEN-LAST:event_jRadioGiaoVienItemStateChanged

    private void jRadioSinhVienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioSinhVienItemStateChanged
        hienThiSV();
    }//GEN-LAST:event_jRadioSinhVienItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_xoaTaiKhoan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edt_maSinhVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioGiaoVien;
    private javax.swing.JRadioButton jRadioSinhVien;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDanhSach;
    // End of variables declaration//GEN-END:variables
}
